apiVersion: v1
kind: Service
metadata:
  name: devops-kubernetes-api-service
  labels:
    app: devops-kubernetes-api
spec:
  selector:
    app: devops-kubernetes-api
  ports:
    - protocol: TCP
      port: 4000 # Service port
      targetPort: 4000 # Container port
  type: NodePort # change to LoadBalancer if running in cloud